name: OrangeScoutFE
description: "Orange Scout's FrontEnd"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter_screenutil: ^5.9.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  geolocator: ^13.0.2 # para a geolocalizacao
  geocoding: ^3.0.0 # para a geolocalizacao
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.5.1 #para o token
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/3PointActionIcon.png
    - assets/images/2PointActionIcon.png
    - assets/images/1PointActionIcon.png
    - assets/images/3PointMissedActionIcon.png
    - assets/images/2PointMissedActionIcon.png
    - assets/images/1PointMissedActionIcon.png
    - assets/images/StealActionIcon.png
    - assets/images/TurnOverActionIcon.png
    - assets/images/BlockActionIcon.png
    - assets/images/AssistActionIcon.png
    - assets/images/OffensiveReboundActionIcon.png
    - assets/images/DefensiveReboundActionIcon.png
    - assets/images/FoulActionIcon.png
    - assets/images/OptionsIcon.png
    - assets/images/SubstitutionActionIcon.png
    - assets/images/Ball.png
    - assets/images/basketball.png
    - assets/images/OrangeScoutLogo.png
    - assets/images/OrangeScoutMain.png
    - assets/images/pngwing.com.png
    - assets/images/TeamsButtonIcon.png
    - assets/images/StartGameButtonIcon.png
    - assets/images/HistoryButtonIcon.png
    - assets/images/TeamsSelectedButtonIcon.png
    - assets/images/StartGameButtonIconSelected.png
    - assets/images/HistoryButtonIconSelected.png
    - assets/images/3x3.png
    - assets/images/5x5.png
    - assets/images/1x1.png
    - assets/images/TeamShieldIcon-cutout.png
    - assets/images/arrow.png
    - assets/images/arrow_left.png
    - assets/images/StatisticsIcon.png
    - assets/images/filterIcon.png
    - assets/images/FinishIcon.png
fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-Bold.ttf
        weight: 700
      - asset: fonts/Inter-Italic.ttf
        style: italic